# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Foundations For Excellence
email: your-email@domain.com
author: Simon Balderson
description: > # this means to ignore newlines until "baseurl:"
  Foundations for Excellence exists to share research, resources and best
  practice for the support and development of talented young musicians, singers
  and dancers. This is currently achieved through the online resource hub, the
  commission of new information sheets on a variety of specific topics and the
  biennial conference.
baseurl: "/FoundationsForExcellence" # the subpath of your site, e.g. /blog
url: "http://foundations-for-excellence.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
# Site settings
permalink: /resources/:title

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
